---
name: GitHub Secretes Demo

on:
  workflow_dispatch:

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message using secret
        run: |
          echo "Your secret token is: ${{secrets.SECRET_TOKEN}}"

      - name: Try to leak it (it will be masked)
        run: |
          echo "Trying to leak the secret....."
          echo "${{secrets.SECRET_TOKEN}}"
