name: Manual Inputs Demo

on: 
  workflow_dispatch:
    inputs:
      name:
        description: "Your name" 
        required: true
        default: 'Ravi'
      age:
        description: "Your age"
        required: false
        default: '30'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print input values
        run: |
          echo "Hello ${{inputs.name}} you are ${{inputs.age}} years old"